# Server configuration
server.port=8082

# PostgreSQL Database configuration
spring.datasource.url=jdbc:postgresql://dpg-d79te715pdvs73bpb8r0-a:5432/my_db_ioct?sslmode=require
spring.datasource.username=my_db_ioct_user
spring.datasource.password=F3wYSH3YvUQ2o3FowENKp7QZgpgXuRFU
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect